language: rust
cache: cargo
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    os: linux
  - env: TARGET=armv7-unknown-linux-gnueabihf
    os: linux
    addons:
      apt:
        packages:
        - gcc-arm-linux-gnueabihf
        - libc6-armhf-cross
        - libc6-dev-armhf-cross
install:
- rustup target add armv7-unknown-linux-gnueabihf
- cargo fetch
script:
- cargo build; cargo test
- cargo build --target=$TARGET --release
before_deploy:
- tar -cvf target/remote-hal-$TARGET-$TRAVIS_TAG.tgz -C target/$TARGET/release/ rhc
  rhd || return 0
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: releases
  api_key:
    secure: kbT870JtNvIKqFxGf4qAz0StYfs0NyyYrl8WNHfI9kJN/pbEvo07S2BmRsWdrEkontwtGey356/DLq92uNsu7WqpipohbKTLBULpgbuOtvG+0D1ieOITPPSpJXcshrgyhG8uQbscxIABnyEuHY4Z7EsoCycoMbfmIy/CwVJ3WuXnRlVqqip0kHip1D/ttOW1f20Xfc55TTCt2z8XZLsCIuaitPH1niA/X/+W00PJ/GmzKrQaNHaBKORLLp9v1gVto/4mv19f45D1VTud69HLVZN4bCAQMkYJxCiUuZydWA0MaJT7IuK0bMIrw6wPTVrtcq2V79I9aMHWu7SbVnE2BZZa4hCPqqqgfPtVqdeccL/8/o1OhMn4/qs1x+S+YG3FxHIUg1448x+d8g4phkEpBNBZVp1GWJQ8rQxIR5gpWevm7BGKFYP9rNqjBAA9lVdw6SlQ1om8Px+1+3pa2gkhsKVU2PdHqVtpVqWSv3IFLy/HTVqj8b0gh2f5ccabq4sqVcH7eUuumc4WlfdXhmVd+EoGxQ5g5oKGdaEFCesK8Bb1JJzizXdctnSUXp5nLC9mONlslWeUyrjzhgJccV30cTbj3L7yqoousx08975FK4PU8KGxqQRiXqiIdgAgyJvhNUcC35CZeBc9c0Hm5rC1FGgfJzdATdshbcUhj48qAMA=
  file: target/*.tgz
  file_glob: true
  draft: true
  on:
    repo: ryankurte/rust-remote-hal
