language: rust
cache: cargo

matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    os: linux
  - env: TARGET=armv7-unknown-linux-gnueabihf
    os: linux
    addons:
      apt:
        packages:
        - gcc-arm-linux-gnueabihf
        - libc6-armhf-cross
        - libc6-dev-armhf-cross

install:
- rustup target add armv7-unknown-linux-gnueabihf
- cargo fetch

script:
- cargo build; cargo test
- cargo build --target=$TARGET --release

before_deploy:
- tar -cvf target/remote-hal-$TARGET-$TRAVIS_TAG.tgz -C target/$TARGET/release/ rhc rhd || return 0

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: releases
  api_key:
  file: target/*.tgz
  file_glob: true
  skip_cleanup: true
  on:
    repo: ryankurte/rust-remote-hal
    tags: true

